services:
  flyway:
    image: "flyway/flyway:latest"
    volumes:
      - ./src/main/resources/db/migrations:/flyway/sql
    env_file:
      - .env
    command: ["migrate", "-url=jdbc:postgresql://db:5432/${POSTGRES_DB}",
              "-user=${POSTGRES_USER}", "-password=${POSTGRES_PASSWORD}"]
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "backend"
    env_file:
      - .env
    ports:
      - "8082:8082"
    depends_on:
      - flyway
      - redis

  frontend:
    build:
      context: .
      dockerfile: front-end/Dockerfile
    container_name: "frontend"
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: "postgres:latest"
    container_name: "database"
    env_file:
      - .env

  redis:
    image: "redis:latest"
    container_name: "redis"
    env_file:
      - .env