server:
  port: 8082
spring:
  jpa:
    hibernate.ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/foodDeliveryProject
    username: postgres
    password: postgrespassnastia