server:
  port: 8082
spring:
  jpa:
    hibernate.ddl-auto: validate
  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  flyway.baseline-on-migrate: true