server:
  port: 8082
spring:
  jpa:
    hibernate.ddl-auto: validate
  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379